# Generated by Django 4.2.7 on 2023-11-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageData",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "classification",
                    models.CharField(
                        choices=[(0, "normal"), (1, "benign"), (2, "malignant")],
                        max_length=15,
                    ),
                ),
                ("image", models.BinaryField()),
                (
                    "set",
                    models.CharField(
                        choices=[(0, "test"), (1, "train"), (2, "validation")],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=15)),
                ("surname", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=40, unique=True)),
                ("password", models.CharField(max_length=15)),
                ("birthDate", models.DateField()),
                ("userId", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                ("imageId", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.BinaryField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groupOneApp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "result",
                    models.CharField(
                        choices=[(0, "low"), (1, "medium"), (2, "high")], max_length=6
                    ),
                ),
                (
                    "timestamp",
                    models.IntegerField(
                        choices=[(0, "beforePrediction"), (0, "afterPrediction")]
                    ),
                ),
                ("predictionId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groupOneApp.userimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groupOneApp.user",
                    ),
                ),
            ],
        ),
    ]
