# Generated by Django 4.2.6 on 2023-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0003_user_token_alter_imagedata_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='classification',
            field=models.IntegerField(choices=[(0, 'benign'), (1, 'malignant'), (2, 'normal')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
