# Generated by Django 4.2.7 on 2023-11-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0004_alter_imagedata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagedata",
            name="image",
            field=models.ImageField(upload_to="image_test"),
        ),
    ]
