# Generated by Django 4.2.3 on 2023-11-30 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0004_alter_imagedata_classification_alter_user_userid"),
        ("groupOneApp", "0006_alter_imagedata_image"),
    ]

    operations = []
