# Generated by Django 4.2.6 on 2023-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groupOneApp', '0007_merge_20231129_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='groupOneApp/image_test'),
        ),
    ]
