# Generated by Django 4.2.7 on 2023-12-01 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0007_merge_20231129_1334"),
        ("groupOneApp", "0007_merge_20231130_1515"),
    ]

    operations = []
