# Generated by Django 4.2.7 on 2023-12-01 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0009_ml_model_alter_imagedata_image"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ml_model",
            table="ML_Models",
        ),
    ]
