# Generated by Django 4.2.3 on 2023-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0007_merge_20231129_1334"),
        ("groupOneApp", "0009_alter_prediction_aftertimestamp_and_more"),
    ]

    operations = []
