# Generated by Django 4.2.7 on 2023-12-01 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0010_alter_ml_model_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ml_model",
            table=None,
        ),
    ]
