# Generated by Django 4.2.7 on 2023-12-01 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0011_alter_ml_model_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ml_model",
            options={"verbose_name": "ML_Model", "verbose_name_plural": "ML_Models"},
        ),
    ]
