# Generated by Django 4.2.7 on 2023-12-01 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0012_alter_ml_model_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagedata",
            options={"verbose_name_plural": "Image data"},
        ),
    ]
