# Generated by Django 4.2.7 on 2023-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0013_alter_imagedata_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ml_model",
            name="snsheatmap",
            field=models.ImageField(upload_to="groupOneApp/ML_models"),
        ),
    ]
