# Generated by Django 4.2.6 on 2023-12-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0008_alter_imagedata_image'),
        ('groupOneApp', '0014_alter_ml_model_snsheatmap'),
    ]

    operations = [
    ]
