# Generated by Django 4.2.6 on 2023-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0015_merge_20231201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
