# Generated by Django 4.2.7 on 2023-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupOneApp", "0016_alter_ml_model_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ml_model",
            name="modelpath",
            field=models.FileField(upload_to="projectOne/cnnModel/models"),
        ),
        migrations.AlterField(
            model_name="ml_model",
            name="snsheatmap",
            field=models.ImageField(upload_to="projectOne/cnnModel/heatMap"),
        ),
    ]
