# Generated by Django 4.2.6 on 2023-12-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0014_alter_prediction_image'),
        ('groupOneApp', '0017_alter_ml_model_modelpath_alter_ml_model_snsheatmap'),
    ]

    operations = [
    ]
