# Generated by Django 4.2.6 on 2023-12-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0018_merge_20231206_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ml_model',
            options={},
        ),
    ]
