# Generated by Django 4.2.6 on 2023-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupOneApp', '0020_rename_accuracy_ml_model_test_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_model',
            name='val_accuracy',
        ),
        migrations.AddField(
            model_name='ml_model',
            name='test_accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
